apiVersion: apps/v1
kind: Deployment
metadata:
  name: goansiblekubernetespipelinescm
spec:
  replicas: 5
  selector:
    matchLabels:
      app: goansiblekubernetespipelinescm
  template:
    metadata:
      labels:
        app: goansiblekubernetespipelinescm
    spec:
      containers:
      - name: goansiblekubernetespipelinescm
        image: pavanshivanand/goansiblekubernetespipelinescm
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
